### PR TITLE
Adding typescript declaration files

### PR DESCRIPTION
**Pull request by codezisland**
Please ensure all pull requests are made against the `develop` branch.

Issue: N/A

Adding typescript declaration files

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cadesalaberry** [comment]
@sapessi what else can we do to get this merged?

**Comment by jbethuel** [comment]
Hi, would be nice if this gets merged. Since we are moving away from aws-serverless-express

**Comment by amedov-denis** [comment]
297nvg

**Comment by chulander** [comment]
i would love this to be merged also

**Comment by EllianCarlos** [comment]
Any updates in this pull request? Would be very nice if this could be merged. Otherwise, adding the package to the `@DefinitelyTyped` repository would also do the job for typescript.

**Comment by aqueleestevao** [comment]
Howdy, folks 🙌🏻 

Please consider merging @amedov-denis `s PR. This will be very important for us who use vendia/serverless-express in Nestjs projects. 

Thanks in advance and for your excellent work as well.

**Comment by carlosasj** [comment]
Hey guys!

Is there any issue stopping this to be merged?

Thanks :smiley:

**Comment by brett-vendia** [comment]
Hey everyone! I'd planned on locking v3 and not publishing any more versions there as we're actively working on v4 with plans on publishing this month, however, it seems like this is quite important to everyone. If someone wants to send a PR against the v3 branch, I'll merge.

I'm no types expert, but are these definitions more complete https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-serverless-express?

**Comment by brettstack** [comment]
Types have been added to `@vendia/serverless-express@4.0.0-rc.5`. The minimum lambda handler for v4 looks like:

```javascript
const serverlessExpress = require('@vendia/serverless-express')
const app = require('./app')

exports.handler = serverlessExpress({
  app,
}).handler
```

**Comment by EllianCarlos** [comment]
> Types have been added to `@vendia/serverless-express@4.0.0-rc.5`. The minimum lambda handler for v4 looks like:
> 
> ```js
> const serverlessExpress = require('@vendia/serverless-express')
> const app = require('./app')
> 
> exports.handler = serverlessExpress({
>   app,
> }).handler
> ```

Thanks! This will help a lot!

**Pull request closed without merging**
