### PR TITLE
add support for apigatewayv2

### PR DESCRIPTION
**Pull request by mirco312312**
_Issue:_
I wanted to use Lambda with API Gateway V2, specifically with `HttpApi` from `@aws-cdk/aws-apigatewayv2` but was unable to get my handlers in the express app called.

**_Description of changes:_**
Updated the code to support payload of V2 Events.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by divmgl** [comment]
Hey! This looks great! You might need to update tests, which is likely why the build is failing. Is this working for you now in production?

**Comment by mirco312312** [comment]
Hey @divmgl 

I updated the integration tests to invoke each test-case for all possible event versions ('1.0' and '2.0' for now).

Also had to fix a unit test that was failing on MacOS.

And by the way your develop branch is behind your master, had to cherry-pick a commit that disables a failing integration test.
=> https://github.com/awslabs/aws-serverless-express/commit/cab6cefd78e742b1e7a90e67f610fd0a6ef20dcd

**Comment by athongintel** [comment]
And no one even merge or take a look. Fuck shit.

**Comment by kgancarz0** [comment]
would love to see this merged...

**Comment by PoofyFoopy** [comment]
How is this not already merged? It would the solve PayloadVersion2 problem

**Comment by Rowanto** [comment]
still any chance for this to be merged?

**Comment by tobilg** [comment]
Ping @DavidWells

**Comment by brett-vendia** [comment]
Hey everyone! Now that I have access to this project again after leaving AWS, this will be supported in the upcoming v4 release. You can check it out on the branch now. Thank you @mirco312312 for this PR. I'd really appreciate your eyes over there to see if I missed anything.

**Comment by brett-vendia** [comment]
Especially the integration tests. If you add those under a new `api-gateway-v2-integration.js` test file that'd be super helpful! v4 has been refactored to make adding additional even sources easy. We also have ALB and Edge over there.

**Comment by brettstack** [comment]
v4 RC is now available with APIGWV2, ALB, Lambda@Edge and more.

**Pull request closed without merging**
